version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: reflex -r '(\.go$$|go\.mod)' -s -- sh -c 'go run main.go'
    ports:
      - "8080:8080"
    volumes:
      - $PWD:/app
    working_dir: /app
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8090:8080"
