FROM golang:1.15.2-alpine as builder

ARG APP_ROOT=/go/src

WORKDIR $APP_ROOT

COPY go.mod go.sum $APP_ROOT
RUN go mod download

COPY . $APP_ROOT

ARG CGO_ENABLED=0
ARG GOOS=linux
ARG GOARCH=amd64
RUN go build -o /go/bin/main -ldflags '-s -w'


FROM scratch as runner
COPY --from=builder /go/bin/main /app/main
EXPOSE 8080
ENTRYPOINT [ "/app/main" ] 